version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - chat-service
      - video-service
      - notification-service

  user-service:
    build: ./services/user-service
    ports:
      - "50051:50051"

  chat-service:
    build: ./services/chat-service
    ports:
      - "50052:50052"

  video-service:
    build: ./services/video-service
    ports:
      - "50053:50053"

  notification-service:
    build: ./services/notification-service
    ports:
      - "50054:50054"
